### ISSUE TITLE
Cursor resets to top of file when telescope closes

### ISSUE THREAD

**Issue by bturloff** [smartpde/telescope-recent-files#9] opened 2023-01-31 05:38 UTC
The cursor is set to the top of the file when the recent files telescope window is closed. The cursor should not move from it's original position.

**Comment by defr0std** [comment] 2023-02-02 20:31
This plugin does not do anything that could cause such behavior. Perhaps this is caused by some other plugin that you have?

**Comment by defr0std** [comment] 2023-09-21 15:28
Closing due to no reply or repro.

**Closed by defr0std** 2023-09-21 15:28 UTC
